In [1]:
import numpy as np
from sympy import *
import numpy.linalg as la

# QR decompoistion
A = QR
Q = M*n dimension matrix orthonormal to column space A(Col A)
R = n * n dimension upper triangular reversible matrix .Diagonal elements are positive.

# calculate the QR decomposition of the following matrix A
A=[<1,1,1,1>, <0,1, 1,1>, <0,0,1,1>]

In [2]:
x1 = np.array([[1],[1],[1],[1]])
x2 = np.array([[0],[1],[1],[1]])
x3 = np.array([[0],[0],[1],[1]])
A = np.hstack([x1,x2,x3])
A

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [3]:
colA = Matrix(A).columnspace()
colA

[Matrix([
 [1],
 [1],
 [1],
 [1]]),
 Matrix([
 [0],
 [1],
 [1],
 [1]]),
 Matrix([
 [0],
 [0],
 [1],
 [1]])]

According to the results above all column vectors of A are basis vectors the Gram-schmidt process is applied to calculate the orthogonal basis of each column space found above.

In [4]:
def orthoCoefS(x, y):
    x=np.dot(x.T, y)
    y=np.dot(y.T, y)
    return(x/y)

In [6]:
v1 = x1

In [7]:
v1

array([[1],
       [1],
       [1],
       [1]])

In [9]:
v2 = x2-orthoCoefS(x2,v1)*v1
v2

array([[-0.75],
       [ 0.25],
       [ 0.25],
       [ 0.25]])

In [11]:
v3 = x3-orthoCoefS(x3,v1)*v1-orthoCoefS(x3,v2)*v2
v3

array([[ 0.        ],
       [-0.66666667],
       [ 0.33333333],
       [ 0.33333333]])

In [12]:
#since q is orthogonal,we modify each vector as a unit vector
v1_u = 1/la.norm(v1)*v1
v2_u = 1/la.norm(v2)*v2
v3_u= 1/la.norm(v3)*v3
Q = np.c_[v1_u,v2_u,v3_u]
np.around(Q,3)

array([[ 0.5  , -0.866,  0.   ],
       [ 0.5  ,  0.289, -0.816],
       [ 0.5  ,  0.289,  0.408],
       [ 0.5  ,  0.289,  0.408]])

In [13]:
AM = np.hstack([Q,A])
np.around(AM,3)

array([[ 0.5  , -0.866,  0.   ,  1.   ,  0.   ,  0.   ],
       [ 0.5  ,  0.289, -0.816,  1.   ,  1.   ,  0.   ],
       [ 0.5  ,  0.289,  0.408,  1.   ,  1.   ,  1.   ],
       [ 0.5  ,  0.289,  0.408,  1.   ,  1.   ,  1.   ]])

In [14]:
AM_rref = Matrix(AM).rref()
np.around(np.array(AM_rref[0],dtype=float),3)

array([[1.   , 0.   , 0.   , 2.   , 1.5  , 1.   ],
       [0.   , 1.   , 0.   , 0.   , 0.866, 0.577],
       [0.   , 0.   , 1.   , 0.   , 0.   , 0.816],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   ]])

In [15]:
AM_rref[1]

(0, 1, 2)

In [18]:
R=np.array(AM_rref[0][:3,3:], dtype=float)
R

array([[2.        , 1.5       , 1.        ],
       [0.        , 0.8660254 , 0.57735027],
       [0.        , 0.        , 0.81649658]])

In [19]:
re = np.dot(Q,R)
np.place(re,re<1e-10,0)
re

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
A ==re

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## The QR decomposition of the matrix can be calculated using the np.linalg.qr() fucntion
This function returns two results:Q and R as tuples. In addition, it may have the opposite sign from the result calculated above,but the final result is the same because the changed sign is commonly applied to Q and R

In [22]:
Q,R = la.qr(A)
np.around(Q,3)

array([[-0.5  ,  0.866,  0.   ],
       [-0.5  , -0.289,  0.816],
       [-0.5  , -0.289, -0.408],
       [-0.5  , -0.289, -0.408]])

In [23]:
np.around(R,3)

array([[-2.   , -1.5  , -1.   ],
       [ 0.   , -0.866, -0.577],
       [ 0.   ,  0.   , -0.816]])

#  Eigen-Decomposition

if a matrix A can be similarly transformed using the reversible matrix P and the diagonal matrix D,..the matrix is said to be diagonalizable.
if all the eigenvalues and eigenvectors are combined,the eigenvalues matrix becomes diagonal.
![](../../../../../../tmp/evince-293600/image.R81PH1.png)
if the eigenmatrix of the above expression is X,matrix A is arranged in the form similarity transformation ..this process is called eigendecomposition of the n * n square matrix.
AX = DX = XD → A = XDX-1

Decompose by applying the above diagonalization to the following
matrix A .
A=[<7,-4>, <2,1>]

In [26]:
A  = np.array([[7,2],[-4,1]])
d, P = la.eig(A)
d

array([5., 3.])

In [27]:
P

array([[ 0.70710678, -0.4472136 ],
       [-0.70710678,  0.89442719]])

In [28]:
D = np.diag(d)
D

array([[5., 0.],
       [0., 3.]])

In [29]:
P_1 = la.inv(P)
P_1

array([[2.82842712, 1.41421356],
       [2.23606798, 2.23606798]])

In [30]:
PDP_1 = np.dot(np.dot(P,D),P_1)
PDP_1

array([[ 7.,  2.],
       [-4.,  1.]])

In [31]:
A == PDP_1

array([[ True,  True],
       [ True,  True]])

Diagonalization is possible if the n * n-dimenstional matrix A has n linearly independent eigenvectors.That is, diagonalization is possible when all eigenvectors are base vectors.


Determine the diagonalization of the next matrxi A,that is the possiblility of eigen-decomposition
A=[<1, -3, 3>, <3, -5, 3>, <3, -3, 1>]

In [32]:
A = np.array([[1,3,3,],[-3,-5,-3],[3,3,1]])
A

array([[ 1,  3,  3],
       [-3, -5, -3],
       [ 3,  3,  1]])

In [33]:
round(la.det(A),3)

4.0

In [34]:
Matrix(A).columnspace()

[Matrix([
 [ 1],
 [-3],
 [ 3]]),
 Matrix([
 [ 3],
 [-5],
 [ 3]]),
 Matrix([
 [ 3],
 [-3],
 [ 1]])]

Since matrix A has a non-zero determinant, an inverse matrix exists and all column vectors are base vectors belonging to the column space.Therefor,this matrix can be diagonalized and decomposed

In [35]:
d,P = la.eig(A)
D = np.diag(d)
D

array([[ 1.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 0.,  0., -2.]])

In [36]:
P

array([[-0.57735027, -0.28310993, -0.39631702],
       [ 0.57735027,  0.80479442, -0.42006444],
       [-0.57735027, -0.52168449,  0.81638146]])

In [37]:
PDP_1 = np.dot(np.dot(P,D),la.inv(P))
PDP_1

array([[ 1.,  3.,  3.],
       [-3., -5., -3.],
       [ 3.,  3.,  1.]])

In [38]:
A == np.around(PDP_1,0)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Spectral decomposition

# Diagonlalization of Symmetric matrix
Eigenvectors corresponding to different eigenvalues have an orthogonal relationship and can be an orthonirmal relationhship

Determine the orthogonality between the eigenvectors of vector A.
A=[<6,-2,-1>, <-2,6,-1>, <-1,-1,5>]

In [50]:
A = np.array([[6,-2,-1],[-2,6,-1],[-1,-1,5]])
A

array([[ 6, -2, -1],
       [-2,  6, -1],
       [-1, -1,  5]])

In [51]:
d, P = la.eig(A)
np.around(P,2)

array([[ 0.58,  0.71, -0.41],
       [ 0.58, -0.71, -0.41],
       [ 0.58,  0.  ,  0.82]])

In [53]:
x1x2=np.around(np.dot(P[:,0],P[:,1].reshape(-1,1)),3)
x1x2

array([-0.])

In [54]:
x1x3=np.around(np.dot(P[:,0],P[:,2].reshape(-1,1)),3)
x1x3

array([-0.])

In [56]:
x2x3=np.around(np.dot(P[:,1],P[:,2].reshape(-1,1)),3)
x2x3

array([-0.])

To Be continued page 162

[1. 0.]
[-1. -0.]
