In [1]:
import numpy as np
import numpy.linalg as la

a = np.array([[2],[1],[-1]])
b = np.array([[-3],[4],[1]])
A = np.hstack((a,b))#used to connect two ojbects in the direction of a column.
A

array([[ 2, -3],
       [ 1,  4],
       [-1,  1]])

In [2]:
m1 = np.array([[2,8],[4,9]])
m2 = np.array([[6,9],[1,0]])
m3 = np.mat([[2,3,4,1]])
M = [m1,m2,m3]
for i,j in zip(M,range(len(M))):
    print(f"shape of {'m'+str(j+1)}{i.shape}")

shape of m1(2, 2)
shape of m2(2, 2)
shape of m3(1, 4)


In [3]:
m1+m2

array([[ 8, 17],
       [ 5,  9]])

# Matrix product

In [4]:
# Establish uT v = vT u on the dot product of two columns or row vectors
#uv=vT uT

In [5]:
u = np.array([-1,2,4]).reshape(3,1)
v = np.array([-2,0,5]).reshape(3,1)
np.equal(np.dot(u.T,v),np.dot(v.T,u))

array([[ True]])

# Special Matrix

## identity matrix
np.eye(n) function used to create n * n dimension identity

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Trace
The sum of the diagonal elements of a square matrix is called the trace of the matrix and is represented by tr(A).
it is calculated using the   np.trace(A)

In [7]:
m = np.random.randint(1,10,(3,3))
m

array([[7, 2, 1],
       [7, 9, 8],
       [6, 9, 5]])

In [8]:
np.trace(m)

21

In [9]:
m_tr = 0
for i in range(m.shape[0]):#0 here main the row.
    m_tr = m_tr + m[i,i]
m_tr

21

## Diagonal matrix
Diagnoal matrices can be created using the np.diag() function

In [10]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Triangular matrix
using np.tril()--> lower
using np.triu()--> upper
note: the transposed matrix of the lower is the upper..and vice versa
irreversible matrix is a matrix that doen't have an inverse matrix...det = 0

In [12]:
x = np.random.randint(1,10,9).reshape((3,3))
x

array([[7, 8, 6],
       [7, 6, 7],
       [9, 5, 8]])

In [13]:
np.triu(x)

array([[7, 8, 6],
       [0, 6, 7],
       [0, 0, 8]])

In [14]:
np.triu(x,k=1)

array([[0, 8, 6],
       [0, 0, 7],
       [0, 0, 0]])

The inverse matrix from the upper triangle matrix and the lower triangle
matrix are the upper triangle matrix and the lower triangle matrix,
respectively

# Symmetric matrix
- it's a square matrix that shows a symmetric relationship with respect to the main diagonal elements.
- A symmetric matrix can be created as the sum of the upper or lower triangular matrix and the transpose matrix of each matrix.

In [15]:
x = np.random.randint(-10,10,(3,3))
y = np.random.randint(-10,10,(3,3))
A = np.triu(x)+np.triu(x).T
A

array([[ 8,  7, -7],
       [ 7, -8,  2],
       [-7,  2, -2]])

In [16]:
A ==A.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Inverse matrix and determinant
A matrix with an inverse matrix is called an invertible matrix and can be calculated by the np.linalg.inv() function
place(object,condition,value) of the numpy ..converts the specified value to the specified condition.


In [17]:
a = np.array([[1,3,-5],[-2,7,8],[4,0,6]])
a_inv =la.inv(a)
a_inv

array([[ 0.13375796, -0.05732484,  0.18789809],
       [ 0.14012739,  0.08280255,  0.00636943],
       [-0.08917197,  0.03821656,  0.04140127]])

In [18]:
np.around(a_inv,2)
re = np.dot(a,a_inv)
re

array([[ 1.00000000e+00,  2.08166817e-17, -6.93889390e-17],
       [ 1.11022302e-16,  1.00000000e+00,  0.00000000e+00],
       [ 5.55111512e-17, -1.38777878e-17,  1.00000000e+00]])

In [19]:
np.place(re,re<1e-10,0)
re

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#ده كود انك تحل الجزئية بتاعت A في b  يسساوي c
# فانت بتجيب معكوس A بعدين تضريه في c علشان يطلعلك الB
A = np.array([[1,1,2],[2,4,-3],[3,6,-5]])
c = np.array([[9],[1],[0]])
A_inv = la.inv(A)
re = np.dot(a_inv,c)
np.around(re,3)

array([[ 1.146],
       [ 1.344],
       [-0.764]])

In [21]:
la.solve(A,c)

array([[1.],
       [2.],
       [3.]])

- the above process is based on the assumption that the coefficient matrix is a square matrix and an inverse matrix exists.
- when the number of unknowns and the number of equations are different,the coefficient matrix is not a square matrix.in this case the inverse matrix cannot be calculated by the above process.
- it calculated by the ** Gaussian Jordan elimination method** can be used to compute the inverse maytrix.
- this elimination method returns a row echelon form matrx.

import sympy as sym
A = sym.Matrix([[1,1,2],[2,4,-3],[3,6,5]])
A.rref()

In [22]:
import sympy as sym
A = sym.Matrix([[1,1,2],[2,4,-3],[3,6,5]])
A.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

# Determinant

In [23]:
a = np.array([[1,1,2],[2,4,-3],[3,6,-5]])
a_inv = la.inv(a)
np.place(a_inv,a_inv<1e-10,0)
a_dit = la.det(a)
a_dit

-1.0000000000000018

- if all elements in one row or column of square matrix A are 0,then the following holds:det(A) = 0
- if the two rows of square matrix A are proportional det(A) = 0
- If the square matrix A is a triangular matrix, the determinant is equal to the product of the principal diagonal element

# LU decomposition
Ax = b
A = LU

In [24]:
A = np.array([[1,-2,3],[2,-5,12],[0,2,-10]])
A

array([[  1,  -2,   3],
       [  2,  -5,  12],
       [  0,   2, -10]])

In [25]:
la.det(A)

-2.0

A = LU → AU-1 = LUU-1 = LI = L

In [26]:
Au = np.triu(A)
Au

array([[  1,  -2,   3],
       [  0,  -5,  12],
       [  0,   0, -10]])

In [27]:
Al = np.dot(A,la.inv(Au))
np.around(Al,2)

array([[ 1.  ,  0.  ,  0.  ],
       [ 2.  ,  0.2 , -0.36],
       [ 0.  , -0.4 ,  0.52]])

In [28]:
np.allclose(A,np.dot(Al,Au))# is used to determine whether the two objects are equal
# Al =L
# Au = U pls focus

True

- LU decomposition can be calculated using linalg.lu() in the scipy library.
- This function should consider the permutation matrix(P)
- A permutation matrix  is simply a matrix that causes a row exchange of results.
- Therefore,the application of this matrix causes a change in the direction or position of each of the upper and lower triangle matrices,but does'n change their essential meaning.

A = PLU
A: Original Matrix
P: Permutation Matrix
L: lower triangular matrix
U: upper triangular matrix

In [29]:
from scipy import linalg
p, l, u=linalg.lu(A)
p

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [30]:
l

array([[1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.5 , 0.25, 1.  ]])

In [31]:
u

array([[  2. ,  -5. ,  12. ],
       [  0. ,   2. , -10. ],
       [  0. ,   0. ,  -0.5]])

In [33]:
np.allclose(A,np.dot(np.dot(p,l),u))

True