In [4]:
import numpy as np
from sympy import *
import pandas as pd

In [5]:
point = np.array([[5,3],[-2,-4],[-3,5],[3,-4]])
point

array([[ 5,  3],
       [-2, -4],
       [-3,  5],
       [ 3, -4]])

In [12]:
a = np.array([1,2])# this is a row  vector
a1 = np.array([[1],[2]])#column vector

In [13]:
print(a)
print(a1)

[1 2]
[[1]
 [2]]


In [14]:
a.ndim

1

In [15]:
a1.ndim

2

In [17]:
a.shape

(2,)

In [18]:
a1.shape

(2, 1)

In [19]:
#brackets([]):refers to the axis
#the number of square brackets within the object determines the dimesnsion

In [21]:
arr= np.array([[3,4,5],[1,46,6]])#there are two brackets ,which means two axes =palne.
arr# two-dimensional of two rows and three columns 2 * 3

array([[ 3,  4,  5],
       [ 1, 46,  6]])

In [24]:
arr.shape

(2, 3)

To convert the structure of an array object ,we apply the np.reshape() function.
the argument of this function is the number of rows and columns to switch
- the number of rows as an argument is -1
- this means that the value is automatically assigned based on the value of the other arguemnt ,the colum.
- in the following cases,the number of rows is automatically adjusted based on the number of columns 2.

In [25]:
arr.reshape(-1,2)

array([[ 3,  4],
       [ 5,  1],
       [46,  6]])

# Norm and Unit vector

In [27]:
#you can use the np.linalg.norm(x) function for norm calculation
import numpy.linalg as la
la.norm([[5,0],[3,0]])

5.830951894845301

In [31]:
a = np.array([[2],[7]])
a_norm = la.norm(a)
a_unit = a/a_norm
print(a_unit)
print("$$$$$$$")
print(la.norm(a_unit))

[[0.27472113]
 [0.96152395]]
$$$$$$$
1.0


## Vector operations

In [33]:
a = np.array([10,15])
b = np.array([8,2])
c = np.array([1,2,3])
a+b

array([18, 17])

In [35]:
a-c

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

## inner product

- The matrix product is calculated using the np.dot(x,y)function.
- The Transposition of an object ..uses obj.T property or np.transpose(obj) function

In [41]:
a = np.array([[2],[7]])
b = np.array([[5],[2]])
print(a.shape)
at = a.T
at.shape

(2, 1)


(1, 2)

In [44]:
innerP = np.dot(at,b)
innerP

array([[24]])

In [46]:
# The dot product (inner product) is the product of the length of vector a and b projected over it
theta = 52.25
rad = np.radians(theta)# the argument passed to numpy's trigonometric functions must be radians.
rad

0.9119345341670372

In [47]:
inner = np.round(la.norm(a)*la.norm(b)*np.cos(rad),0)
inner

24.0

In [49]:
a = np.array([[-2],[1]])
b = np.array([[-3],[1]])
#inner product between a and b
ab = np.dot(a.T,b)
#norm of  a
a_norm = la.norm(a)
#norm of b
b_norm = la.norm(b)
cos = ab/(a_norm*b_norm)
cos

array([[0.98994949]])

In [50]:
rad = np.arccos(cos)
rad

array([[0.14189705]])

In [51]:
deg = np.rad2deg(rad)
deg

array([[8.13010235]])

- in the above process,np.arccos() and np.rad2deb() functions were used to calculate theta.
- x=cos(y)→y=cos${-1}$(x)
- cos${-1}$ is calculated by the arccos() function
الي هو السؤال بتاع ايه الزاوية الي الكوزين بتاعها بكذا ؟

# orthogonal vectors

- when the dot product is zero ..these vectors are called *orthogonal vectors*
- If two vectors u · v = 0, the two vectors are orthogonal.
- The 0 vector is orthogonal to all vectors.

# Cauchy-schwars inequality
‖uv‖ ≤ ‖u‖‖v‖

In [54]:
u = np.array([[-1],[2]])
v = np.array([[4],[-2]])
inner = np.dot(u.T,v)
abs(inner)

array([[8]])

In [55]:
normProd = la.norm(u)*la.norm(v)
round(normProd,3)

10.0

# Projections


In [57]:
ab_d = np.dot(a.T,b)
a_norm = (la.norm(a))**2
b_proj = ab_d/a_norm*2
b_proj

array([[2.8]])

# Outer product

- vectors that are perendicular to any two vectors are produced by cross product.
a×b = <a2 b3 -a3 b2 , a3 b1 -a1 b3 , a1 b2 -a2 b1 >
- the above equation calculated using the np.cross()

In [63]:
a = np.array([[2],[1],[-1]])
b = np.array([[-3],[4],[1]])
np.cross(a.T,b.T)

array([[ 5,  1, 11]])

if the two vectors are parallel ..the cross product of the two vectors cannot exist