# Kernal and Range
transform refers to a function that assigns a number x to expression and returns y,the result corresponding to that value.
the range and number of values entered into the function cannot always determine the range or number of results.
that is depending on the function,one real input value may be output as a value containing  muliple rationl numbers.
The input range function is called the domain
and the range of all possilbe output is called the codomain.
The result of  a fucntion in the codomain is called the image,and the set of these images is called the range.
Range is a subset of codomain.

![](../../../../../../tmp/evince-293600/image.OA3GH1.png)

## Relationship between domain,codomain,and range.
- injective (one-to-one)
- subjective(onto):range = codomain
- bijective: in case of one-to-one correspondence and co-domain and range are the same


The domain in which all the ranges of these linear transformations are zero is called the kernel.
when the range of is all 0,the domain is called the kernel.

A transformation that is bijective adn takes place in the same dimension is called isomorphism...in other words the dimension of the domain and the codomain are the same.

if it has a trivial solution,it means one-to-one reaction and is injective.


In [22]:
import numpy as np
from sympy import *
import numpy.linalg as la

In [23]:
A = np.array([[0,1],[1,0]])
la.det(A)

-1.0

In [24]:
c = np.zeros([2,1])
Matrix(np.hstack([A,c])).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0]]),
 (0, 1))

the determinant of standard matrix A is not 0,and the rref of that matrix incidates that all column vectors of A are pivot columns.
in other words,the standard matrix A is  reversible matrix and has a trivial solution.
therefore,the above transformation is injective.

let's decide if the next transofrmation is injective.
T: R3 →R3
T(x, y, z) = (x+2y-z, y+z, x+y-2z)

In [25]:
A = np.array([[1,2,-1],[0,1,1],[1,1,-2]])
la.det(A)

0.0

In [26]:
c = np.zeros([3,1])
Matrix(np.hstack([A,c])).rref()# the result shows that it is not injecitve

(Matrix([
 [1, 0, -3.0, 0],
 [0, 1,  1.0, 0],
 [0, 0,    0, 0]]),
 (0, 1))

## Ker T = 0
- this transformation is injective
- it has a trivial solution and is linear independent

Let's decide how to respond between domain and codomain by the
following matrix.
T(<x, y, z>) = <x, y>
T = [<1, 0>, <0, 1>, <0, 0>

![](../../../../../../tmp/evince-293600/image.F47PH1.png)


The above expression is satisfied for all numbers in z.in other words,
it is not injective because there are various solutions.
However,the number of equations and the number of solutions are the same.in other words, it is subjective because it has the same codaomian and range.
Not all subjectis are injective .However, to be injective, it must be subjective.
that is,in order for the number of variables to match the number of solutions,the number of expressions must be equal to or greater than the number of solutions.

Column and row vectors of A are linearly independent.
⇔ Ax = 0 has a trivial solution.
⇔ Ax = b has a unique solution.
⇔ A is reversible and det (A) ≠ 0.
⇔ λ = 0 is not an eigenvalue of A.
⇔ T is bijective

# linear Transformation
is a function to move on e vector space U to another vector space V.

In [27]:
A = np.array([[2,0,1],[0,-4,0]])
A

array([[ 2,  0,  1],
       [ 0, -4,  0]])

In [28]:
Matrix(A).rref()#A is a linearly dependent containing one free varibalbe,and a linear combination is established

(Matrix([
 [1, 0, 1/2],
 [0, 1,   0]]),
 (0, 1))

In [29]:
a = np.array([3,6,9])
b = np.array([2,5,8])
def trans1(x):
    x1 = 2 * x[0]+x[2]
    x2 = -4*x[1]
    return(np.array([x1,x2]))
#T(a) + T(b)  = T(a+b)
trans1(a+b) == trans1(a)+trans1(b)


array([ True,  True])

In [30]:
6*trans1(a) == trans1(6*a)

array([ True,  True])

The above transformation is a linear transformation because it staisfies the two conditions of the transformation
linear combination is a requirement for linear transformation.that is not all linear combination satisfy the linear transformation .

# Special linear transform
1. linear transformation in the same dimension
2. shifting a certain angle
3.

In [31]:
#shifiting a ceratin angle
rad = np.cos(np.deg2rad(45))
R = np.array([[np.cos(rad),-np.sin(rad)],[np.sin(rad),np.cos(rad)]])
np.round(R,3)

array([[ 0.76, -0.65],
       [ 0.65,  0.76]])

In [32]:
b = np.array([[3],[2]])
c = np.dot(R,b)
np.around(c,3)

array([[0.981],
       [3.469]])

# orthogonal set and projection

## Orhogonal set
if the dot product of a vector is 0,the vector is orthogonal ..the set {u1,u2,...,up} of all vectors with zero dot product in the R$^n$ dimension is called an orhtogonal set.
linear combination by a standard matrix of orthogonal vectors is linear independent and a one-to-one response,or injective.

## Orthogonal Projection

In [37]:
z = np.array([[7],[6]])
u = np.array([[4],[2]])
zu= np.dot(z.T,u)
zu

array([[40]])

In [39]:
uu = np.dot(u.T,u)
uu

array([[20]])

In [40]:
hat_u = zu/uu*u
hat_u

array([[8.],
       [4.]])

In [41]:
v = z-hat_u
v

array([[-1.],
       [ 2.]])

![](../../../../../../tmp/evince-293600/image.506IH1.png)
an vector can be decomposed into two vector perpendicular to each other using orthogonal projection

# Orthogomal

unit vectors orthogonal to each other are called orthonormal.
Unit vectors orthogonal to each other are called orthonomal and becomes basis vectors.


# Gram-schmidt process

The Gram process is a simple algorithm that generates an orthogonal ro orthonomal basis in a subspace of R$^n$ that is not zero.

when W = span{x1,x2} determine the orthogonal basis{v1,v2}
x1 = (3,6,0)
x2 = (1,2,2)
![](../../../../../../tmp/evince-293600/image.LPPEH1.png)
As shown the orthogonal basis of space W can be represesnted by v1, v2 and vector x2 is projected orthogonally onto vector x1 .in other words,you can assume the relationship v1 = x1,so x2 can be decomposed as
x2 = v2 +p
in the above equation p is calculated using orthogonal basis x1 = v1, and it is calculated as follows

![](../../../../../../tmp/evince-293600/image.DKAFH1.png)

In [43]:
x1 = np.array([3,6,0]).reshape(-1,1)
x2 = np.array([1,2,2]).reshape(-1,1)
def orthoCoefS(x,y):
    x = np.dot(x.T,y)
    y = np.dot(y.T,y)
    return(x/y)
p = orthoCoefS(x2,x1)*x1
p

array([[1.],
       [2.],
       [0.]])

In [45]:
v2 = x2 -p
v2

array([[0.],
       [0.],
       [2.]])

In [46]:
x2 == p+v2

array([[ True],
       [ True],
       [ True]])

x2 is the subspace of the space with basis vectors v1,v2 as Span

# to be continue..

### similarity transformation
the two matrices by similar transformation have the same
characteristic equation and the same characteristic value.

# Diagonalization
in many cases, the eigenvalues and eignevectors of matrix A are useful for creating factorization(decomposition) such as the similarity transformation.
Diagonal matrices are very useful for calculations ..as follows: for example the power of a diagonal matrix is equal to the power of the diagonal elements of the diagonal matrix

In [50]:
A = np.array([[5,0],[0,5]])
np.dot(A,A)# as a result the exponential power of the diagonal elements can be generalized as

array([[25,  0],
       [ 0, 25]])

![](../../../../../../tmp/evince-293600/image.273DH1.png)

A = [< 7, -4 >, < 2, 1 >]
P = [< 1,-1 >, < 1, -2 >]
D = [< 5, 0 >, < 0, 3 >]

In [52]:
A = np.array([[7,2],[-4,1]])
A

array([[ 7,  2],
       [-4,  1]])

In [53]:
P = np.array([[1,1],[-1,-2]])
D = np.array([[5,0],[0,3]])
A ==np.dot(np.dot(P,D),la.inv(P))

array([[ True,  True],
       [ True,  True]])

## The exponentail power of an array object can be calculated using the linalg.matrix_power() function

In [55]:
D3 = np.array([[5**3,0],[0,3**3]])
A3 = np.dot(np.dot(P,D3),la.inv(P))
A3

array([[ 223.,   98.],
       [-196.,  -71.]])

In [62]:
la.matrix_power(A,3)

array([[ 223,   98],
       [-196,  -71]])