#### The symbols() function from the sympy library--> this function converts symbols to unknwons that can be calculated,so various operations involving unkowns are possible.

In [3]:
import numpy as np
from sympy import *

v1 = < 1, -2, -2 >
v2 = < 15, -4, -7 >
v3 = < -3, 1, 0 >
c= < -4, 3, h

In [4]:
v1 = np.array([1,-2,-2]).reshape(-1,1)
v2 = np.array([5,-4,7]).reshape(-1,1)
v3 = np.array([-3,1,0]).reshape(-1,1)
V = np.hstack([v1,v2,v3])
V

array([[ 1,  5, -3],
       [-2, -4,  1],
       [-2,  7,  0]])

In [5]:
h = symbols("h")
y = Matrix([[-4],[3],[h]])
y

Matrix([
[-4],
[ 3],
[ h]])

au = Matrix(V).row_join(y)
au

In [9]:
au.rref()

(Matrix([
 [1, 0, 0,     -h/7 - 5/7],
 [0, 1, 0, 5*h/49 - 10/49],
 [0, 0, 1, 6*h/49 + 37/49]]),
 (0, 1, 2))

- Each column vector of the identity matrix is linearly indepnedent of all vectors....This vector is called the standard basis.
- if the vectors show the identity matrix in the rref,they are the basis.

# Null space and column space

In [10]:
A = np.array([[1,-3,-2],[-5,9,1]])
A

array([[ 1, -3, -2],
       [-5,  9,  1]])

In [11]:
u = np.array([5,3,-2]).reshape(-1,1)
u

array([[ 5],
       [ 3],
       [-2]])

In [12]:
np.dot(A,u)

array([[0],
       [0]])

The null space can be checked using the function nullspace() from the sympy
- the result of this function returns the column vector(s)

In [16]:
A = np.array([[-3,6,-1,1,-7],[1,-2,2,3,-1],[2,-4,5,8,-4]])
nul_A = Matrix(A).nullspace()
nul_A

[Matrix([
 [2],
 [1],
 [0],
 [0],
 [0]]),
 Matrix([
 [ 1],
 [ 0],
 [-2],
 [ 1],
 [ 0]]),
 Matrix([
 [-3],
 [ 0],
 [ 2],
 [ 0],
 [ 1]])]

In [17]:
re = nul_A[0]
for i in range(1,len(nul_A)):
    re = np.hstack([re,nul_A[i]])
re

array([[2, 1, -3],
       [1, 0, 0],
       [0, -2, 2],
       [0, 1, 0],
       [0, 0, 1]], dtype=object)

# Column Space

the column space of the matrix can be checked by the sympy columnspace() function

In [20]:
col_A =Matrix(A).columnspace()
col_A

[Matrix([
 [-3],
 [ 1],
 [ 2]]),
 Matrix([
 [-1],
 [ 2],
 [ 5]])]